CREATE TABLE CLIENTES(
	DNI CHAR(9) CONSTRAINT PK_DNI PRIMARY KEY,
	NOMBRE  VARCHAR2(20) NOT NULL,
    APELLIDOS VARCHAR2(40) NOT NULL,
    RESIDENCIA VARCHAR2(80) NOT NULL
);

CREATE TABLE VEHICULOS(
    MATRICULA CHAR(7) CONSTRAINT PK_MAT PRIMARY KEY,
    MODELO VARCHAR2(30) NOT NULL,
    MARCA VARCHAR2(30) NOT NULL,
    DNI CHAR(9) CONSTRAINT FK_DNI REFERENCES CLIENTES(DNI)
);

CREATE TABLE FACTURA(
    NUMFACTURA VARCHAR2(12) CONSTRAINT PK_NFACTURA PRIMARY KEY,
    FE_EMISION DATE NOT NULL,
    FE_PAGO DATE NOT NULL,
    TRABAJADOR VARCHAR2(25) NOT NULL,
    MATRICULA CHAR(7) CONSTRAINT FK_MATRICULA REFERENCES VEHICULOS(MATRICULA)
);

CREATE TABLE REPUESTOS(
    REFERENCIA NUMBER (7,0) CONSTRAINT PK_REPUESTOS PRIMARY KEY,
    DESCRIPCION VARCHAR2(50) NOT NULL,
    IMPORTE NUMBER (5,2) NOT NULL,
    GANANCIA NUMBER (5,2) NOT NULL
);


CREATE TABLE DETFACTURA (
    NUMFACTURA VARCHAR2(12) CONSTRAINT PK_NDETFACTURA PRIMARY KEY
    CONSTRAINT FK_NFACTURA REFERENCES FACTURA(NUMFACTURA),
    UNIDADES NUMBER(2,0) NOT NULL,
    REFERENCIA NUMBER (7,0) CONSTRAINT FK_REFERENCIA REFERENCES REPUESTOS(REFERENCIA)
);