CREATE TABLE CLIENTES(
    DNI CHAR(9) CONSTRAINT PK_DNI PRIMARY KEY,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDOS VARCHAR2(40) NOT NULL,
    RESIDENCIA VARCHAR2(80) NOT NULL,
    FE_NACIMIENTO DATE NOT NULL,
    TELEF NUMBER(9,0) NOT NULL,
    CUENTA_BANCARIA NUMBER (8,1),
    IS_TITULAR CHAR(1) CHECK(IS_TITULAR IN ('S','N')) NOT NULL
);

CREATE TABLE VEHICULOS(
    MATRICULA CHAR(7) CONSTRAINT PK_MATRICULA PRIMARY KEY,
    MODELO VARCHAR2(30) NOT NULL,
    MARCA VARCHAR2(30) NOT NULL,
    NUM_GARAJE NUMBER(5) NOT NULL,
    FE_INGRESO DATE NOT NULL,
    POTENCIA_MOTOR NUMBER(5,1),
    DNI CHAR(9) CONSTRAINT FK_DNI REFERENCES CLIENTES(DNI),
    ASEGURADO CHAR(1) CHECK(ASEGURADO IN ('S','N')) NOT NULL
);

CREATE TABLE FACTURA(
    NUMFACTURA NUMBER(7) CONSTRAINT PK_NUMFACTURA PRIMARY KEY,
    FE_EMISION DATE NOT NULL,
    FE_PAGO DATE,
    NHORAS NUMBER(4,2),
    MATRICULA CHAR(7) CONSTRAINT FK_MATRICULA REFERENCES VEHICULOS(MATRICULA),
    PAGADA CHAR(1) CHECK(PAGADA IN ('S','N')) NOT NULL
);

CREATE TABLE REPUESTOS(
    REFERENCIA VARCHAR (7) CONSTRAINT PK_REFERENCIA PRIMARY KEY,
    DESCRIPCION VARCHAR2(50) NOT NULL,
    IMPORTE NUMBER (5) NOT NULL,
    GANANCIA NUMBER(7,3) NOT NULL,
    FE_SOLICITUD DATE NOT NULL, 
    IN_STOCK CHAR(1) CHECK(IN_STOCK IN ('S','N')) NOT NULL
);

CREATE TABLE DETFACTURA (
    NUMFACTURA NUMBER(7),    
    UNIDADES NUMBER(2,0) NOT NULL,
    REFERENCIA VARCHAR (7) NOT NULL,
    CONSTRAINT PK_DETNUMFACTURA PRIMARY KEY (NUMFACTURA, REFERENCIA),
    CONSTRAINT FK_NUMFACTURA FOREIGN KEY (NUMFACTURA) REFERENCES FACTURA(NUMFACTURA),
    CONSTRAINT FK_REFERENCIA FOREIGN KEY (REFERENCIA) REFERENCES REPUESTOS(REFERENCIA)
);
